show databases;
create database address_book_system;
use address_book_system;
select database();
create table contacts(person_id int not null auto_increment, first_name varchar(250) not null, last_name varchar(250)not null, city varchar(250) not null,state varchar(250)not null,phone_number bigint(14) not null, email varchar(250)not null, zip_code int(10)not null, primary key(person_id));
desc contacts;
insert into contacts(first_name, last_name, city, state, phone_number, email, zip_code) values ('Javul', 'mulla', 'belgaum', 'karnataka', 987543210, 'javulmulla@gmail.com', 123456),('akash', 'p', 'chennai', 'tamilnadu', 987543211, 'akashp@gmail.com', 123457),('Thilak', 'm', 'bengalore', 'karnataka', 987543212, 'thilakm@gmail.com', 123458),('Syed', 'D', 'mysore', 'karnataka', 987543213, 'syedd@gmail.com', 123459),('Roshan', 'H', 'mumbai', 'maharashtra', 987543213, 'roshanh@gmail.com', 123459);
select * from contacts;
update contacts set city = 'belgaum' where name = 'Syed';
select * from contacts;
delete from contacts where first_name = 'Roshan';
select * from contacts;
select * from contacts where city = 'belgaum';
select count(state) from contacts;
select * from contacts where city = 'belgaum' order by 'first_name';
alter table contacts add type varchar(250) after  last_name;
select * from contacts;
insert into contacts(first_name, last_name, city, state, phone_number, email, zip_code) values ('Roshan', 'H', 'belgaum', 'karnataka', 987543214, 'roshanh@gmail.com', 123460);
update contacts set type = 'family' where first_name = 'Javul';
update contacts set type = 'family' where first_name = 'Syed';
update contacts set type = 'freinds' where first_name = 'Roshan';
update contacts set type = 'freinds' where first_name = 'akash';
update contacts set type = 'profession' where first_name = 'Thilak';
select * from contacts;
select type, count(first_name) from contacts group by type;
insert into contacts(first_name, last_name, type, city, state, phone_number, email, zip_code) values ('Praveen', 'B', 'freind', 'bagalkot', 'karnataka', 987543215, 'praveenb@gmail.com', 123461),('Amjad', 'H', 'family', 'hospet', 'karnataka', 987543216, 'amjadh@gmail.com', 123462);
select * from contacts;
